---
title: "Marketing App"
output: flexdashboard::flex_dashboard
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(rmarkdown)
library(knitr)
library(Hmisc)
library(DT)
library(data.table)

assignInNamespace("cedta.override", c(data.table:::cedta.override,"rmarkdown"), "data.table")

opts_chunk$set(echo = FALSE, comment="", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=55), tidy = TRUE)

```


```{r read_data, include=FALSE}
dat <- fread(input = "C:/Users/taita/Documents/Research Library/Data Science/Github/Marketing Survey App/Homework 3 Data.csv", verbose = FALSE)
```


```{r constants}
id.name <- "id"
age.name <- "Age"
gender.name <- "Gender"
income.name <- "Income"
region.name <- "Region"
persona.name <- "Persona"

product.name <- "Product"
awareness.name <- "Awareness"
consideration.name <- "Consideration"
consumption.name <- "Consumption"
satisfaction.name <- "Satisfaction"
advocacy.name <- "Advocacy"
Aggregated.Engagement.name <- "Aggregated.Engagement"
pattern.bp <- "BP_"

age.group.name <- "Age Group"
income.group.name <- "Income Group"

cuts.age <- c(18, 35, 50, 65, 120)
cuts.income <- 1000* c(0, 50, 75, 100, 150, 250)
negative_perceptions <- c("BP_Boring_0_10","BP_Bulky_0_10" ,"BP_Fragile_0_10","BP_Expensive_0_10")
dat[, eval(age.group.name) := cut2(x = get(age.name), cuts = cuts.age)]
dat[, eval(income.group.name) := cut2(x = get(income.name), cuts = cuts.income)]
dat[, eval(satisfaction.name) := get(satisfaction.name)/10]

unique.age.groups <- dat[, unique(get(age.group.name))]
unique.genders <- dat[, unique(get(gender.name))]
unique.income.groups <- dat[, unique(get(income.group.name))]
unique.regions <- dat[, unique(get(region.name))]
unique.personas <- dat[, unique(get(persona.name))]

unique.products <- dat[, unique(get(product.name))]
num.products <- length(unique.products)

respondent.variables <- c(age.group.name, gender.name, income.group.name, region.name, persona.name)
states.of.engagement <- c(awareness.name, consideration.name, consumption.name, satisfaction.name, advocacy.name)
bp.traits <- names(dat)[grep(pattern = pattern.bp, x = names(dat))]
```

```{r functions}
percentage.table <- function(x, digits = 1){
  tab <- table(x)
  percentage.tab <- 100*tab/(sum(tab))
  rounded.tab <- round(x = percentage.tab, digits = digits)
  return(rounded.tab)
}

round.numerics <- function(x, digits){
  if(is.numeric(x)){
    x <- round(x = x, digits = digits)
  }
  return(x)
}
mean.diff <- function(x, y){
  return(mean(x, na.rm=TRUE) - mean(y, na.rm=TRUE))
}

create.formula <- function(outcome.name, input.names, input.patterns = NA, all.data.names = NA, return.as = "character"){
  
  variable.names.from.patterns <- c()
  if(!is.na(input.patterns[1]) & !is.na(all.data.names[1])){
    pattern <- paste(input.patterns, collapse = "|")
    variable.names.from.patterns <- all.data.names[grep(pattern = pattern, x = all.data.names)]
  }
  all.input.names <- unique(c(input.names, variable.names.from.patterns))
  all.input.names <- all.input.names[all.input.names != outcome.name]
  
  if(!is.na(all.data.names[1])){
    all.input.names <- all.input.names[all.input.names %in% all.data.names]
  }

  input.names.delineated <- sprintf("`%s`", all.input.names)
  the.formula <- sprintf("`%s` ~ %s", outcome.name, paste(input.names.delineated, collapse = "+"))
  
  if(return.as == "formula"){
    return(as.formula(the.formula))
  }
  if(return.as != "formula"){
    return(the.formula)
  }
}

fit.model <- function(dt, outcome.name, input.names, model.type, digits = 3){
  the.formula <- reduce.formula(dt = dt, outcome.name = outcome.name, input.names = input.names)
  
  if(model.type == "logistic"){
    mod <- glm(formula = the.formula, family = "binomial", data = dt)
    mod.summary <- logistic.regression.summary(glm.mod = mod, digits = digits)
  }
  if(model.type == "linear"){
    mod <- lm(formula = the.formula, data = dt)
    mod.summary <- linear.regression.summary(glm.mod = mod, digits = digits)
  }
  mod.summary.rounded <- mod.summary[, lapply(X = .SD, FUN = "round.numerics", digits = digits)]
  return(mod.summary.rounded)
}
```


Introduction
=====================================  

We are analyzing data from the Marketing Department covering a variety of mobile phone products.  

The survey was given to `r dat[, length(unique(get(id.name)))]` respondents and covered `r num.products` separate products.

Click on the tabs to see different reports.


Question 1
===================================


Row {data-height=500}
-------------------------------------

```{r respondents}
inputPanel(
    selectInput(inputId="respondent_variable", label = "Select Variable:", choices = respondent.variables, selected = respondent.variables[1]),
  checkboxInput(inputId = "respondent_show_percentages", label = "Show Percentages", value = TRUE)
)

renderPlot({
  tab <- percentage.table(x = dat[get(product.name) == get(product.name)[1], get(input$respondent_variable)])
  barplot(height = tab, space=0.01, las = 1, main = input$respondent_variable, ylab = "Percentage", xlab = input$respondent_variable, ylim = c(0, 1.2*max(tab, na.rm = TRUE)), col = "dodgerblue")
  
  if(input$respondent_show_percentages == TRUE){
    space_val = 0
    text(x = -0.4 + 1:length(tab) * (1+space_val), y = tab, labels = sprintf("%.1f%%", tab), pos = 3)
  }
})
```

Question 2
=====================================  


Row {data-height=800}
-------------------------------------

```{r products}
inputPanel(
    selectInput(inputId = "product_info_engagement_state", label = "Select State of Engagement:", choices = states.of.engagement, selected = states.of.engagement[1]),
    selectInput(inputId="em_age_group", label = "Age", choices = unique.age.groups, selected = unique.age.groups, multiple = TRUE),
    selectInput(inputId = "em_gender", label = "Gender", choices = unique.genders, selected = unique.genders, multiple = TRUE),
    selectInput(inputId = "em_income_group", label = "Income", choices = unique.income.groups, selected = unique.income.groups, multiple = TRUE),
    selectInput(inputId = "em_region", label = "Region", choices = unique.regions, selected = unique.regions, multiple = TRUE),
    selectInput(inputId = "em_persona", label = "Persona", choices = unique.personas, selected = unique.personas, multiple = TRUE),
    sliderInput(inputId = "show_data_threshold", label = "Choose Number of Products to Show", min = 1, max = 20, value = 5, step = 1)
)

renderPlot({
  subdat <- dat[get(age.group.name) %in% input$em_age_group & get(gender.name) %in% input$em_gender & get(income.group.name) %in% input$em_income_group & get(region.name) %in% input$em_region & get(persona.name) %in% input$em_persona]
  tab <- subdat[,.(Sum = 100*sum(get(input$product_info_engagement_state), na.rm=TRUE)/
                      length(!is.na(get(input$product_info_engagement_state)))), by = product.name]
  setorderv(x = tab, cols = "Sum", order = -1)
  tab <- tab[1:input$show_data_threshold]
  barplot(height = tab[,Sum], space=0.01, las = 1, names.arg = tab[, get(product.name)], ylab = sprintf("Rate of %s", input$product_info_engagement_state), xlab  = "Brand", ylim = c(0, 1.2*max(tab[,Sum], na.rm=TRUE)), col = "dodgerblue")
    space_val = 0
    text(x = -0.4 + 1:nrow(tab) * (1+space_val), y = tab[,Sum], labels = sprintf("%.1f%%", tab[,Sum]), pos = 3)
})
```


Question 3
=====================================  

Row {data-height=500}
-------------------------------------

```{r brand_perceptions}
inputPanel(
  selectInput(inputId="bp_age_group", label = "Age Group", choices = unique.age.groups, selected = unique.age.groups, multiple = TRUE),
  selectInput(inputId = "bp_gender", label = "Gender", choices = unique.genders, selected = unique.genders, multiple = TRUE),
  selectInput(inputId = "bp_income_group", label = "Income Group", choices = unique.income.groups, selected = unique.income.groups, multiple = TRUE),
  selectInput(inputId = "bp_region", label = "Region", choices = unique.regions, selected = unique.regions, multiple = TRUE),
  selectInput(inputId = "bp_persona", label = "Persona", choices = unique.personas, selected = unique.personas, multiple = TRUE),

  sliderInput(inputId = "bp_Top_products", label = "# of Products shown", min = 0, max = 20, value = 5, step = 1)
)

renderPlot({
  subdat <- dat[get(age.group.name) %in% input$bp_age_group & get(gender.name) %in% input$bp_gender & get(income.group.name) %in% input$bp_income_group & get(region.name) %in% input$bp_region & get(persona.name) %in% input$bp_persona]
  dat_bp <- subdat[,lapply(X = .SD, FUN = function(x)mean(x, na.rm = TRUE)), .SDcols = bp.traits, by = product.name]
  dat_bp_negative <- dat_bp[,lapply(X = .SD, FUN = function(x)(10-x)), .SDcols = negative_perceptions]
  dat_inverted_average <- cbind(dat_bp[,1:9],dat_bp_negative)
  dat_bp_overall <- dat_inverted_average[, .(Product = get(product.name), Overall_average = rowMeans(dat_inverted_average[,2:13],na.rm = TRUE))]
  setorderv(x = dat_bp_overall, cols = "Overall_average",-1)
  selected_bp_overall <- dat_bp_overall[1:input$bp_Top_products]
  sub_bp_overall <- selected_bp_overall[, Overall_average := round(x = Overall_average, digits = 1)]

  barplot <- barplot(height = sub_bp_overall[,Overall_average], space=0.01, las = 1, main = sprintf("Top %s brands of overall average perception", input$bp_Top_products), ylab = "Overall average perception", ylim = c(0, 12), xaxt = "n", axes = F, col = "dodgerblue")
  axis(side = 2, at = 2*(0:5), las = 2)
  
  text(barplot, par("usr")[3], labels = sub_bp_overall[, get(product.name)], srt = 45, adj = c(1.1,1.1), xpd = TRUE)
  
  space_val = 0
  text(x = -0.4 + 1:sub_bp_overall[,.N] * (1+space_val), y = sub_bp_overall[,Overall_average], labels = sub_bp_overall[,Overall_average], pos = 3)
})
```



Question 4
=====================================  

Row {data-height=500}
-------------------------------------

```{r engagement_plots}

inputPanel(
  selectInput(inputId="q4_state1", label = "Select First Outcome:", choices = states.of.engagement, selected = states.of.engagement[1]),
  selectInput(inputId="q4_state2", label = "Select Second Outcome:", choices = states.of.engagement, selected = states.of.engagement[2]), 
  selectInput(inputId = "q4_num_of_products", label = "Number of products to display", choices = (1:num.products), selected = 5),
  checkboxInput(inputId = "q4_show_percentages", label = "Show Percentages", value = TRUE),
  selectInput(inputId="q4_digits", label = "Select Number of digits to display:", choices = c(1:6), selected = 1)
)

renderPlot({
  if(input$q4_state1 == satisfaction.name){
    tab=dat[,.(gap = 10*  ( mean  (get(input$q4_state1), na.rm=TRUE))- 100*( mean( get(input$q4_state2), na.rm=TRUE) ) ), by=product.name]
  }
    if(input$q4_state2 == satisfaction.name){
    tab=dat[,.(gap = 100*  ( mean  (get(input$q4_state1), na.rm=TRUE))- 10*( mean( get(input$q4_state2), na.rm=TRUE) ) ), by=product.name]
    }
    if(input$q4_state1 == satisfaction.name & input$q4_state2 == satisfaction.name){
    tab=dat[,.(gap = 10*(mean(get(input$q4_state1), na.rm=TRUE))- 10*(mean(get(input$q4_state2), na.rm=TRUE))), by=product.name]
  }
  else{
    tab=dat[,.(gap = 100*  ( mean  (get(input$q4_state1), na.rm=TRUE))- 100*( mean( get(input$q4_state2), na.rm=TRUE) ) ), by=product.name]
  }
  
  setorderv(x = tab, cols = "gap", order = -1)

  barplot(height = tab[1:input$q4_num_of_products, gap], space=0.01, las = 1, main = sprintf("Gap between %s and %s", input$q4_state1, input$q4_state2),ylab = "Percentage", ylim = c(-0.7*max(tab[,gap],na.rm=T), 1.3*max(tab[,gap], na.rm=TRUE)), col = "dodgerblue")
  
    text(x = -0.5 + 1.02*1:tab[1:input$q4_num_of_products, .N], y = -7, labels = tab[1:input$q4_num_of_products, get(product.name)], srt = 45, pos = 2)

  
  if(input$q4_show_percentages == TRUE){
    space_val = 0
    text(x = -0.4 + 1:tab[1:input$q4_num_of_products, .N] * (1+space_val), y = tab[1:input$q4_num_of_products, gap], labels = paste(round( tab[1:input$q4_num_of_products, gap], as.numeric(input$q4_digits)),"%"), pos = 3)
  }
})



```

Question 5
=====================================  

Row {data-height=300}
-------------------------------------


```{r engagement_models}
inputPanel(
  selectInput(inputId = "em_product", label = "Select Product:", choices = unique.products, selected = product.name[1]),
  selectInput(inputId = "em_engagement_state", label = "Select State of Engagement:", choices = states.of.engagement, selected = states.of.engagement[1]),
  selectInput(inputId="em_inputs", label = "Choose Inputs:", choices = c(age.group.name, gender.name, income.group.name, region.name, persona.name, bp.traits, Aggregated.Engagement.name), selected = c(age.group.name, gender.name, income.group.name, region.name, persona.name, Aggregated.Engagement.name), multiple = TRUE)
)


renderDataTable({

  pattern.names <- list()
  for (i in 1:length(bp.traits)){
    pattern.names[[i]] <- names(dat)[grep(pattern = bp.traits[i],x = names(dat))]
   }

  subtable1 <- dat[get(product.name) == input$em_product,.SD,.SDcols = c(id.name, product.name, input$em_engagement_state, as.character(pattern.names), age.group.name, gender.name, income.group.name, region.name, persona.name)]
  subtable2 <- dat[get(product.name) != input$em_product,.(mean(get(input$em_engagement_state),na.rm = TRUE)),by = id]
  setnames(x = subtable2, old = "V1", new = eval(Aggregated.Engagement.name))
  
  aggregated_tab <- merge(subtable1,subtable2,by = eval(id.name))
  
  alpha = 0.05
  z <- qnorm(p = 1-alpha/2, mean = 0, sd = 1)

  outcome.name <- eval(input$em_engagement_state)

  if(input$em_engagement_state == awareness.name){
    input.name <- input$em_inputs[!input$em_inputs %in% bp.traits]
    }

  if(input$em_engagement_state != awareness.name){
    input.name <- input$em_inputs
    }

  formula <- sprintf("`%s` ~ %s", outcome.name, paste(lapply(input.name, FUN = function(x)sprintf("`%s`", x)), collapse = "+"))

  if (input$em_engagement_state == satisfaction.name){
    model <- lm(formula = as.formula(formula), data = aggregated_tab)
    model_coefs <- as.data.table(summary(model)$coefficients, keep.rownames = TRUE)
    model_coefs[, Coef.Lower.95 := Estimate - z * `Std. Error`]
    model_coefs[, Coef.Upper.95 := Estimate + z * `Std. Error`]

  }

  if (input$em_engagement_state != satisfaction.name){
    model <- glm(formula = as.formula(formula), family = "binomial", data = aggregated_tab)
    model_coefs <- as.data.table(summary(model)$coefficients, keep.rownames = TRUE)
    model_coefs[, Odds.Ratio := exp(Estimate)]
    model_coefs[, OR.Lower.95 := exp(Estimate - z * `Std. Error`)]
    model_coefs[, OR.Upper.95 := exp(Estimate + z * `Std. Error`)]

  }
  datatable(model_coefs[,lapply(X = .SD,FUN = "round.numerics", digits = 3)])
})

```

Row {data-height=700}
-------------------------------------
